---------------------------------------------------------------------------------------------------
-- Copyright (c) 2026 by Julian Schneider
-- Authors: Julian Schneider
---------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------
-- Description
---------------------------------------------------------------------------------------------------
-- Register map of the MIB: addresses, field positions and reset values of the AXI4-Lite registers.
-- Generated by tools/regmap.py from hdl/owr_mib/regs/owr_regs.yml, do not edit.
--
-- Documentation: hdl/owr_mib/docs/register_map.md

---------------------------------------------------------------------------------------------------
-- Libraries
---------------------------------------------------------------------------------------------------
library ieee;
    use ieee.std_logic_1164.all;

---------------------------------------------------------------------------------------------------
-- Package Header
---------------------------------------------------------------------------------------------------
package owr_regs_pkg is

    -----------------------------------------------------------------------------------------------
    -- Identification
    -----------------------------------------------------------------------------------------------
    constant RegMapId_c : std_logic_vector(31 downto 0) := x"4F575201";

    -----------------------------------------------------------------------------------------------
    -- Register addresses (byte addresses)
    -----------------------------------------------------------------------------------------------
    constant RegId_c          : natural := 16#00#;
    constant RegGenerics_c    : natural := 16#04#;
    constant RegFifoDepths_c  : natural := 16#08#;
    constant RegClkFreq_c     : natural := 16#0C#;
    constant RegPortCtrl_c    : natural := 16#10#;
    constant RegLinkSpeed_c   : natural := 16#14#;
    constant RegPortStatus_c  : natural := 16#18#;
    constant RegCredit_c      : natural := 16#1C#;
    constant RegFifoLevels_c  : natural := 16#20#;
    constant RegErrors_c      : natural := 16#24#;
    constant RegErrorCounts_c : natural := 16#28#;
    constant RegLinkCounts_c  : natural := 16#2C#;
    constant RegEvents_c      : natural := 16#30#;
    constant RegErrorsIrqEn_c : natural := 16#34#;
    constant RegEventsIrqEn_c : natural := 16#38#;
    constant RegIrqStatus_c   : natural := 16#3C#;
    constant RegTimeCode_c    : natural := 16#40#;
    constant RegTcSend_c      : natural := 16#44#;
    constant RegTcCounts_c    : natural := 16#48#;
    constant RegIntCtrl_c     : natural := 16#50#;
    constant RegIntTick_c     : natural := 16#54#;
    constant RegIntHoldoff_c  : natural := 16#58#;
    constant RegIntAckDelay_c : natural := 16#5C#;
    constant RegIntActive_c   : natural := 16#60#;
    constant RegIntSend_c     : natural := 16#64#;
    constant RegIntAck_c      : natural := 16#68#;
    constant RegAckReceived_c : natural := 16#6C#;
    constant RegEccStatus_c   : natural := 16#80#;
    constant RegEccSelect_c   : natural := 16#84#;
    constant RegEccCount_c    : natural := 16#88#;
    constant RegEccInject_c   : natural := 16#8C#;

    -----------------------------------------------------------------------------------------------
    -- Fields: bit of a one-bit field, lowest and highest bit of a wider field
    -----------------------------------------------------------------------------------------------

    constant IdIdLo_c : natural := 0;
    constant IdIdHi_c : natural := 31;

    constant GenericsTimeCodes_c       : natural := 0;
    constant GenericsInterrupts_c      : natural := 1;
    constant GenericsIntTimerWidthLo_c : natural := 8;
    constant GenericsIntTimerWidthHi_c : natural := 12;

    constant FifoDepthsTxLo_c : natural := 0;
    constant FifoDepthsTxHi_c : natural := 15;
    constant FifoDepthsRxLo_c : natural := 16;
    constant FifoDepthsRxHi_c : natural := 31;

    constant ClkFreqKhzLo_c : natural := 0;
    constant ClkFreqKhzHi_c : natural := 31;

    constant PortCtrlPortReset_c    : natural := 0;
    constant PortCtrlLinkDisabled_c : natural := 1;
    constant PortCtrlLinkStart_c    : natural := 2;
    constant PortCtrlAutoStart_c    : natural := 3;
    constant PortCtrlDriverEn_c     : natural := 4;
    constant PortCtrlReceiverEn_c   : natural := 5;
    constant PortCtrlLoopback_c     : natural := 6;

    constant LinkSpeedRunDivLo_c  : natural := 0;
    constant LinkSpeedRunDivHi_c  : natural := 7;
    constant LinkSpeedInitDivLo_c : natural := 8;
    constant LinkSpeedInitDivHi_c : natural := 15;

    constant PortStatusLinkStateLo_c : natural := 0;
    constant PortStatusLinkStateHi_c : natural := 2;
    constant PortStatusRecovery_c    : natural := 3;
    constant PortStatusGotNull_c     : natural := 4;
    constant PortStatusSpill_c       : natural := 5;
    constant PortStatusLastCauseLo_c : natural := 8;
    constant PortStatusLastCauseHi_c : natural := 10;

    constant CreditTxCreditLo_c : natural := 0;
    constant CreditTxCreditHi_c : natural := 5;
    constant CreditRxCreditLo_c : natural := 8;
    constant CreditRxCreditHi_c : natural := 13;

    constant FifoLevelsTxLo_c : natural := 0;
    constant FifoLevelsTxHi_c : natural := 15;
    constant FifoLevelsRxLo_c : natural := 16;
    constant FifoLevelsRxHi_c : natural := 31;

    constant ErrorsDisconnect_c : natural := 0;
    constant ErrorsParity_c     : natural := 1;
    constant ErrorsEsc_c        : natural := 2;
    constant ErrorsCredit_c     : natural := 3;

    constant ErrorCountsDisconnectLo_c : natural := 0;
    constant ErrorCountsDisconnectHi_c : natural := 7;
    constant ErrorCountsParityLo_c     : natural := 8;
    constant ErrorCountsParityHi_c     : natural := 15;
    constant ErrorCountsEscLo_c        : natural := 16;
    constant ErrorCountsEscHi_c        : natural := 23;
    constant ErrorCountsCreditLo_c     : natural := 24;
    constant ErrorCountsCreditHi_c     : natural := 31;

    constant LinkCountsRunLo_c      : natural := 0;
    constant LinkCountsRunHi_c      : natural := 15;
    constant LinkCountsRecoveryLo_c : natural := 16;
    constant LinkCountsRecoveryHi_c : natural := 31;

    constant EventsLinkUp_c          : natural := 0;
    constant EventsLinkDown_c        : natural := 1;
    constant EventsTcValid_c         : natural := 2;
    constant EventsTcInvalid_c       : natural := 3;
    constant EventsIntReceived_c     : natural := 4;
    constant EventsAckReceived_c     : natural := 5;
    constant EventsBcDiscarded_c     : natural := 6;
    constant EventsBcIgnored_c       : natural := 7;
    constant EventsIntReqDiscarded_c : natural := 8;
    constant EventsAckReqDiscarded_c : natural := 9;
    constant EventsIndOverflow_c     : natural := 10;
    constant EventsRxOverflow_c      : natural := 11;
    constant EventsEccSec_c          : natural := 12;
    constant EventsEccDed_c          : natural := 13;

    constant ErrorsIrqEnEnableLo_c : natural := 0;
    constant ErrorsIrqEnEnableHi_c : natural := 3;

    constant EventsIrqEnEnableLo_c : natural := 0;
    constant EventsIrqEnEnableHi_c : natural := 13;

    constant IrqStatusIrq_c : natural := 0;

    constant TimeCodeValueLo_c : natural := 0;
    constant TimeCodeValueHi_c : natural := 5;

    constant TcSendValueLo_c : natural := 0;
    constant TcSendValueHi_c : natural := 5;

    constant TcCountsValidLo_c   : natural := 0;
    constant TcCountsValidHi_c   : natural := 15;
    constant TcCountsInvalidLo_c : natural := 16;
    constant TcCountsInvalidHi_c : natural := 31;

    constant IntCtrlAckMode_c : natural := 0;

    constant IntTickCyclesLo_c : natural := 0;
    constant IntTickCyclesHi_c : natural := 15;

    constant IntHoldoffTicksLo_c : natural := 0;

    constant IntAckDelayTicksLo_c : natural := 0;

    constant IntActiveIidLo_c : natural := 0;
    constant IntActiveIidHi_c : natural := 31;

    constant IntSendIidLo_c : natural := 0;
    constant IntSendIidHi_c : natural := 4;

    constant IntAckIidLo_c : natural := 0;
    constant IntAckIidHi_c : natural := 4;

    constant AckReceivedIidLo_c : natural := 0;
    constant AckReceivedIidHi_c : natural := 31;

    constant EccStatusDedLo_c : natural := 0;
    constant EccStatusDedHi_c : natural := 5;

    constant EccSelectChannelLo_c : natural := 0;
    constant EccSelectChannelHi_c : natural := 2;

    constant EccCountSecLo_c : natural := 0;
    constant EccCountSecHi_c : natural := 15;
    constant EccCountDedLo_c : natural := 16;
    constant EccCountDedHi_c : natural := 31;

    constant EccInjectChannelLo_c : natural := 0;
    constant EccInjectChannelHi_c : natural := 2;
    constant EccInjectSingle_c    : natural := 8;
    constant EccInjectDouble_c    : natural := 9;

    -----------------------------------------------------------------------------------------------
    -- Reset values of the registers whose fields all have a fixed reset value
    -----------------------------------------------------------------------------------------------
    constant RegErrorsReset_c      : std_logic_vector(31 downto 0) := x"00000000";
    constant RegErrorCountsReset_c : std_logic_vector(31 downto 0) := x"00000000";
    constant RegLinkCountsReset_c  : std_logic_vector(31 downto 0) := x"00000000";
    constant RegEventsReset_c      : std_logic_vector(31 downto 0) := x"00000000";
    constant RegErrorsIrqEnReset_c : std_logic_vector(31 downto 0) := x"00000000";
    constant RegEventsIrqEnReset_c : std_logic_vector(31 downto 0) := x"00000000";
    constant RegTcSendReset_c      : std_logic_vector(31 downto 0) := x"00000000";
    constant RegTcCountsReset_c    : std_logic_vector(31 downto 0) := x"00000000";
    constant RegIntCtrlReset_c     : std_logic_vector(31 downto 0) := x"00000000";
    constant RegIntSendReset_c     : std_logic_vector(31 downto 0) := x"00000000";
    constant RegIntAckReset_c      : std_logic_vector(31 downto 0) := x"00000000";
    constant RegAckReceivedReset_c : std_logic_vector(31 downto 0) := x"00000000";
    constant RegEccStatusReset_c   : std_logic_vector(31 downto 0) := x"00000000";
    constant RegEccSelectReset_c   : std_logic_vector(31 downto 0) := x"00000000";
    constant RegEccCountReset_c    : std_logic_vector(31 downto 0) := x"00000000";
    constant RegEccInjectReset_c   : std_logic_vector(31 downto 0) := x"00000000";

end package;
