# ---------------------------------------------------------------------------------------------------
# Copyright (c) 2026 by Julian Schneider
# Authors: Julian Schneider
# ---------------------------------------------------------------------------------------------------
"""Register map of the OpenWire MIB, generated from one description.

Reads hdl/owr_mib/regs/owr_regs.yml and writes

- hdl/owr_pkg/src/owr_regs_pkg.vhd   VHDL package: addresses, field positions, reset values
- hdl/owr_mib/docs/register_map.md   documentation of every register and field
- sw/owr_regs.h                      C header for the software

python tools/regmap.py          writes the generated files
python tools/regmap.py --check  fails when a generated file does not match the description (CI)
"""

import argparse
import difflib
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "hdl" / "owr_mib" / "regs" / "owr_regs.yml"
VHDL = ROOT / "hdl" / "owr_pkg" / "src" / "owr_regs_pkg.vhd"
DOC = ROOT / "hdl" / "owr_mib" / "docs" / "register_map.md"
HEADER = ROOT / "sw" / "owr_regs.h"

ACCESS = {
    "RO": "Read only",
    "RW": "Read and write",
    "W1": "Write one: command; reads as zero",
    "W1C": "Sticky flag; write one to clear",
    "WO": "Write only; reads as zero",
    "RC": "Read only; any write to the register clears it",
}

GENERATED = "Generated by tools/regmap.py from hdl/owr_mib/regs/owr_regs.yml, do not edit."


class Field:
    def __init__(self, d):
        self.name = d["name"]
        self.access = d["access"]
        assert self.access in ACCESS, self.access
        self.reset = d.get("reset")
        self.description = d["description"]
        bits = str(d["bits"])
        if ":" in bits:
            hi, lo = bits.split(":")
            self.lo = int(lo)
            self.hi = int(hi) if hi.isdigit() else None  # None: width depends on a generic
        else:
            self.lo = self.hi = int(bits)
        self.bits = bits

    @property
    def single(self):
        return self.hi == self.lo

    @property
    def mask(self):
        return (1 << (self.hi - self.lo + 1)) - 1


class Register:
    def __init__(self, d, array=None):
        self.name = d["name"]
        self.offset = d["offset"]
        self.description = d["description"]
        self.fields = [Field(f) for f in d["fields"]]
        self.array = array
        self.address = (array["base"] if array else 0) + self.offset

    @property
    def reset(self):
        """Reset value of the register, None when a field has no fixed reset value."""
        value = 0
        for f in self.fields:
            if not isinstance(f.reset, int) or f.hi is None:
                return None
            value |= f.reset << f.lo
        return value


def load():
    d = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    regs = [Register(r) for r in d["registers"]]
    arrays = []
    for a in d.get("arrays", []):
        arrays.append((a, [Register(r, a) for r in a["registers"]]))
    return d["id"], regs, arrays


def camel(name):
    return "".join(p.capitalize() for p in name.lower().split("_"))


def addr_text(reg):
    if reg.array:
        a = reg.array
        index = "n"
        return f"0x{reg.address:03X} + 0x{a['stride']:X} {index}"
    return f"0x{reg.address:02X}"


def reset_text(f):
    if f.reset is None:
        return ""
    if isinstance(f.reset, int):
        return f"0x{f.reset:X}" if f.reset > 9 else str(f.reset)
    return str(f.reset)


# -----------------------------------------------------------------------------------------------------
# VHDL package
# -----------------------------------------------------------------------------------------------------
def aligned(decls, indent="    "):
    """Constant declarations (name, type, value) with aligned colons and assignments."""
    wn = max(len(n) for n, _, _ in decls)
    wt = max(len(t) for _, t, _ in decls)
    return [f"{indent}constant {n:<{wn}} : {t:<{wt}} := {v};" for n, t, v in decls]


def section(title):
    return ["    " + "-" * 95, f"    -- {title}", "    " + "-" * 95]


def vhdl(reg_id, regs, arrays):
    lines = [
        "-" * 99,
        "-- Copyright (c) 2026 by Julian Schneider",
        "-- Authors: Julian Schneider",
        "-" * 99,
        "",
        "-" * 99,
        "-- Description",
        "-" * 99,
        "-- Register map of the MIB: addresses, field positions and reset values of the AXI4-Lite registers.",
        f"-- {GENERATED}",
        "--",
        "-- Documentation: hdl/owr_mib/docs/register_map.md",
        "",
        "-" * 99,
        "-- Libraries",
        "-" * 99,
        "library ieee;",
        "    use ieee.std_logic_1164.all;",
        "",
        "-" * 99,
        "-- Package Header",
        "-" * 99,
        "package owr_regs_pkg is",
        "",
    ]
    lines += section("Identification")
    lines += aligned([("RegMapId_c", "std_logic_vector(31 downto 0)", f'x"{reg_id:08X}"')])
    lines.append("")
    lines += section("Register addresses (byte addresses)")
    lines += aligned([(f"Reg{camel(r.name)}_c", "natural", f"16#{r.address:02X}#") for r in regs])
    for a, aregs in arrays:
        lines.append("")
        lines += section(f"{a['name']} registers: address of instance n = Reg<Name>_c + n * "
                         f"Reg{camel(a['name'])}Stride_c")
        decls = [(f"Reg{camel(a['name'])}Base_c", "natural", f"16#{a['base']:03X}#"),
                 (f"Reg{camel(a['name'])}Stride_c", "natural", f"16#{a['stride']:03X}#")]
        decls += [(f"Reg{camel(r.name)}_c", "natural", f"16#{r.address:02X}#") for r in aregs]
        decls += [(f"Reg{camel(r.name)}Ofs_c", "natural", f"16#{r.offset:02X}#") for r in aregs]
        lines += aligned(decls)
    lines.append("")
    lines += section("Fields: bit of a one-bit field, lowest and highest bit of a wider field")
    for r in regs + [r for _, aregs in arrays for r in aregs]:
        decls = []
        for f in r.fields:
            base = f"{camel(r.name)}{camel(f.name)}"
            if f.single:
                decls.append((f"{base}_c", "natural", str(f.lo)))
            else:
                decls.append((f"{base}Lo_c", "natural", str(f.lo)))
                if f.hi is not None:
                    decls.append((f"{base}Hi_c", "natural", str(f.hi)))
        lines.append("")
        lines += aligned(decls)
    lines.append("")
    lines += section("Reset values of the registers whose fields all have a fixed reset value")
    decls = [(f"Reg{camel(r.name)}Reset_c", "std_logic_vector(31 downto 0)", f'x"{r.reset:08X}"')
             for r in regs + [r for _, aregs in arrays for r in aregs]
             if r.reset is not None and any(f.access != "RO" for f in r.fields)]
    lines += aligned(decls)
    lines += ["", "end package;", ""]
    return "\n".join(lines)


# -----------------------------------------------------------------------------------------------------
# Documentation
# -----------------------------------------------------------------------------------------------------
def markdown(reg_id, regs, arrays):
    lines = [
        "# owr_mib: Register Map",
        "",
        f"{GENERATED.replace('tools/regmap.py', '`tools/regmap.py`').replace('hdl/owr_mib/regs/owr_regs.yml', '`hdl/owr_mib/regs/owr_regs.yml`')}",
        "The same description generates the VHDL package `owr_regs_pkg` and the C header `sw/owr_regs.h`.",
        "",
        "Byte addresses of 32-bit registers on the AXI4-Lite port (8-bit address); unused addresses and bits read as "
        "zero.",
        f"The ID register reads 0x{reg_id:08X}.",
        "",
        "| Access | Meaning |",
        "| --- | --- |",
    ]
    lines += [f"| {k} | {v} |" for k, v in ACCESS.items()]
    lines += ["", "## Registers", "", "| Address | Register | Description |", "| --- | --- | --- |"]
    allregs = regs + [r for _, aregs in arrays for r in aregs]
    lines += [f"| {addr_text(r)} | [{r.name}](#{r.name.lower()}) | {r.description} |" for r in allregs]
    for a, _ in arrays:
        lines += ["", f"{a['description']}, for {a['count']} instances."]
    lines += ["", "## Fields"]
    for r in allregs:
        lines += ["", f"### {r.name}", "", f"Address {addr_text(r)}: {r.description}.", "",
                  "| Bits | Field | Access | Reset | Description |", "| --- | --- | --- | --- | --- |"]
        for f in sorted(r.fields, key=lambda f: -f.lo):
            lines.append(f"| {f.bits} | {f.name} | {f.access} | {reset_text(f)} | {f.description} |")
    lines.append("")
    return "\n".join(lines)


# -----------------------------------------------------------------------------------------------------
# C header
# -----------------------------------------------------------------------------------------------------
def defines(items):
    w = max(len(n) for n, _ in items)
    return [f"#define {n:<{w}} {v}" for n, v in items]


def header(reg_id, regs, arrays):
    lines = [
        "/*",
        " * Copyright (c) 2026 by Julian Schneider",
        " * Authors: Julian Schneider",
        " *",
        " * Register map of the OpenWire MIB (AXI4-Lite, byte addresses of 32-bit registers).",
        f" * {GENERATED}",
        " */",
        "",
        "#ifndef OWR_REGS_H",
        "#define OWR_REGS_H",
        "",
        "/* Identification */",
    ]
    lines += defines([("OWR_REGMAP_ID", f"0x{reg_id:08X}u")])
    lines += ["", "/* Register addresses */"]
    lines += defines([(f"OWR_{r.name}", f"0x{r.address:02X}u") for r in regs])
    for a, aregs in arrays:
        index = "n"
        lines += ["", f"/* {a['description']} */"]
        items = [(f"OWR_{a['name']}_STRIDE", f"0x{a['stride']:03X}u")]
        items += [(f"OWR_{r.name}({index})", f"(0x{r.address:03X}u + ({index}) * 0x{a['stride']:03X}u)") for r in aregs]
        lines += defines(items)
    lines += ["", "/* Fields: position (SHIFT) and mask after the shift (MASK); fields with a generic width have no mask */"]
    for r in regs + [r for _, aregs in arrays for r in aregs]:
        items = []
        for f in r.fields:
            items.append((f"OWR_{r.name}_{f.name}_SHIFT", f"{f.lo}u"))
            if f.hi is not None:
                items.append((f"OWR_{r.name}_{f.name}_MASK", f"0x{f.mask:X}u"))
        lines += [""] + defines(items)
    lines += ["", "/* Reset values of the registers whose fields all have a fixed reset value */"]
    items = [(f"OWR_{r.name}_RESET", f"0x{r.reset:08X}u") for r in regs + [r for _, aregs in arrays for r in aregs]
             if r.reset is not None and any(f.access != "RO" for f in r.fields)]
    lines += defines(items)
    lines += ["", "#endif /* OWR_REGS_H */", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail when a generated file is not up to date")
    args = parser.parse_args()
    reg_id, regs, arrays = load()
    outputs = {VHDL: vhdl(reg_id, regs, arrays), DOC: markdown(reg_id, regs, arrays), HEADER: header(reg_id, regs, arrays)}
    stale = []
    for path, text in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != text:
            stale.append(path)
            if args.check:
                diff = difflib.unified_diff(current.splitlines(), text.splitlines(), str(path), "generated", lineterm="", n=1)
                print("\n".join(list(diff)[:40]))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    rel = [str(p.relative_to(ROOT)) for p in stale]
    if args.check:
        if stale:
            print("Not up to date (run python tools/regmap.py):", ", ".join(rel))
            return 1
        print("Register map outputs up to date")
        return 0
    print("Written:", ", ".join(rel) if rel else "nothing (up to date)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
